name = "ComputedGeodesicEquations"
uuid = "42910a5e-bdf1-4870-a538-dfa35571a56d"
authors = ["fjebaker <fergusbkr@gmail.com>"]
version = "0.1.0"

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
