name = "ComputedGeodesicEquations"
uuid = "42910a5e-bdf1-4870-a538-dfa35571a56d"
authors = ["fjebaker <fergusbkr@gmail.com>"]
version = "0.3.0"

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
JuliaFormatter = "^0.18.0"
Parameters = "^0.12.0"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
